name: Test Secret

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test if secret exists
      run: |
        if [ -z "${{ secrets.LOAN_PASSWORD }}" ]; then
          echo "❌ LOAN_PASSWORD secret is NOT set!"
          echo "Go to Settings > Secrets and variables > Actions"
          echo "Add a new secret named LOAN_PASSWORD"
        else
          echo "✅ LOAN_PASSWORD secret IS set!"
          echo "Length: ${#LOAN_PASSWORD} characters"
          echo "First character: ${LOAN_PASSWORD:0:1}"
          echo "Last character: ${LOAN_PASSWORD: -1}"
        fi
      env:
        LOAN_PASSWORD: ${{ secrets.LOAN_PASSWORD }}