name: Debug Password Issue

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Debug the exact issue
      env:
        LOAN_PASSWORD: ${{ secrets.LOAN_PASSWORD }}
      run: |
        echo "=== DEBUGGING THE REPLACEMENT ISSUE ==="
        
        echo "1. Password info:"
        echo "   Length: ${#LOAN_PASSWORD}"
        echo "   Value: '$LOAN_PASSWORD'"
        
        echo "2. Looking for the exact string in file:"
        if grep -q "GITHUB_SECRET_PASSWORD" index.html; then
          echo "   ✅ Found GITHUB_SECRET_PASSWORD"
          echo "   Line containing it:"
          grep -n "GITHUB_SECRET_PASSWORD" index.html
        else
          echo "   ❌ GITHUB_SECRET_PASSWORD not found"
        fi
        
        echo "3. Show the exact CORRECT_PASSWORD line:"
        grep -n "CORRECT_PASSWORD" index.html
        
        echo "4. Testing sed replacement directly:"
        echo "   Before: $(grep "CORRECT_PASSWORD" index.html)"
        
        # Try the replacement
        sed -i "s/GITHUB_SECRET_PASSWORD/$LOAN_PASSWORD/g" index.html
        
        echo "   After:  $(grep "CORRECT_PASSWORD" index.html)"
        
        echo "5. Check if placeholder still exists:"
        if grep -q "GITHUB_SECRET_PASSWORD" index.html; then
          echo "   ❌ STILL EXISTS! Replacement failed!"
          
          echo "6. Let's see what went wrong:"
          echo "   Checking for any encoding issues..."
          hexdump -C index.html | grep -A 5 -B 5 "GITHUB_SECRET_PASSWORD" || echo "   Not found in hex dump"
          
          echo "   Full line around CORRECT_PASSWORD:"
          grep -A 3 -B 3 "CORRECT_PASSWORD" index.html
          
        else
          echo "   ✅ Success! Placeholder removed"
          echo "   New password is set to: $(grep "CORRECT_PASSWORD" index.html | cut -d'"' -f4)"
        fi
        
        echo "7. Final verification - what's the actual password value:"
        node -e "
        const fs = require('fs');
        const content = fs.readFileSync('index.html', 'utf8');
        const match = content.match(/const CORRECT_PASSWORD = \"([^\"]+)\"/);
        if (match) {
          console.log('Password found in file:', match[1]);
        } else {
          console.log('No password constant found');
        }
        "