name: Deploy Dashboard

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Debug and replace password
      env:
        LOAN_PASSWORD: ${{ secrets.LOAN_PASSWORD }}
      run: |
        # Debug: Check if secret is set
        if [ -z "$LOAN_PASSWORD" ]; then
          echo "ERROR: LOAN_PASSWORD secret is not set in repository settings!"
          echo "Please go to Settings > Secrets and variables > Actions and add LOAN_PASSWORD"
          exit 1
        fi
        
        echo "LOAN_PASSWORD secret is set (length: ${#LOAN_PASSWORD} characters)"
        
        # Check if placeholder exists
        if grep -q "GITHUB_SECRET_PASSWORD" index.html; then
          echo "Found password placeholder, replacing..."
        else
          echo "Password placeholder not found in index.html"
          exit 1
        fi
        
        # Simple replacement - escape special characters in password
        # Use perl for more reliable replacement
        perl -pi -e "s/GITHUB_SECRET_PASSWORD/\Q$ENV{LOAN_PASSWORD}\E/g" index.html
        
        # Verify replacement worked
        if grep -q "GITHUB_SECRET_PASSWORD" index.html; then
          echo "ERROR: Password replacement failed!"
          exit 1
        else
          echo "Password replacement successful!"
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4