name: Verify Deployed File

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Show original file
      run: |
        echo "=== ORIGINAL FILE FROM REPOSITORY ==="
        echo "Line 29 (CORRECT_PASSWORD):"
        sed -n '29p' index.html
        echo ""
        
    - name: Replace password
      env:
        LOAN_PASSWORD: ${{ secrets.LOAN_PASSWORD }}
      run: |
        echo "=== REPLACING PASSWORD ==="
        echo "Before replacement:"
        grep -n "CORRECT_PASSWORD.*=" index.html
        
        sed -i "s/GITHUB_SECRET_PASSWORD/$LOAN_PASSWORD/g" index.html
        
        echo "After replacement:"
        grep -n "CORRECT_PASSWORD.*=" index.html
        echo ""
        
    - name: Show modified file content
      run: |
        echo "=== MODIFIED FILE CONTENT ==="
        echo "Lines 25-35 of modified file:"
        sed -n '25,35p' index.html
        echo ""
        echo "Searching for any remaining placeholder:"
        if grep -q "GITHUB_SECRET_PASSWORD" index.html; then
          echo "❌ PLACEHOLDER STILL EXISTS!"
          grep -n "GITHUB_SECRET_PASSWORD" index.html
        else
          echo "✅ No placeholder found - replacement successful"
        fi
        echo ""
        
    - name: Create verification file
      run: |
        echo "=== CREATING VERIFICATION FILE ==="
        # Create a simple verification file to confirm this version is deployed
        echo "Deployment verification: $(date)" > deployment-check.txt
        echo "Password replaced: $(date)" >> deployment-check.txt
        grep "CORRECT_PASSWORD.*=" index.html >> deployment-check.txt
        
        echo "Verification file created:"
        cat deployment-check.txt
        echo ""
        
    - name: List files being deployed
      run: |
        echo "=== FILES BEING DEPLOYED ==="
        ls -la
        echo ""
        echo "Size of index.html: $(wc -c < index.html) bytes"
        echo "Modified time: $(stat -c %y index.html)"
        echo ""
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Post-deployment verification
      run: |
        echo "=== POST-DEPLOYMENT ==="
        echo "Deployed to: ${{ steps.deployment.outputs.page_url }}"
        echo "You should now check:"
        echo "1. Visit: ${{ steps.deployment.outputs.page_url }}/deployment-check.txt"
        echo "2. View source of: ${{ steps.deployment.outputs.page_url }}"
        echo "3. Look for the CORRECT_PASSWORD line around line 29"